### ISSUE TITLE
[Request] Prepare plugin documentation for Packer.io ingestion

### ISSUE THREAD

**Issue by nywilken** [UpCloudLtd/packer-plugin-upcloud#11]
Hello UpCloud team, fellow Packer maintainer here interested in helping getting the UpCloud builder registered on Packer.io. 

Plugin documentation for third party plugins can be automatically ingested by the Packer.io build job, by adding an entry for a third party plugin [here](https://github.com/hashicorp/packer/blob/master/website/data/docs-remote-plugins.json).

But before, the documentation can be consumed there are few things that need to be done on the plugin side. 
 - [x] Place plugin documentation into a separate `docs` directory with a sub-directory for each component type. - See [Packer Plugin Scaffolding](https://github.com/hashicorp/packer-plugin-scaffolding/tree/main/docs) for examples.
 - [x] Packer plugin documentation as a zip file along side the plugin releases in a file called docs.zip - In the scaffolding repo we have an example [goreleaser file](https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.goreleaser.yml) with configuration on line 12, and 82 for including the docs.zip within the plugin release. 
 - [x] Once the documentation is ready, and being released along side the plugin binaries you can open a Pull request against Packer with an entry for the UpCloud builder in the [remote-docs file](https://github.com/hashicorp/packer/blob/master/website/data/docs-remote-plugins.json).

### Note
This plugin doesn't currently have a lot of configuration options. But you may find it helpful to know that the Packer team has released, as part of the Packer Plugin SDK, a `packer-sdc` command that can be used for generating documentation for plugin configuration options using code comments - please see the command documentation [here](https://github.com/hashicorp/packer-plugin-sdk/tree/main/cmd/packer-sdc/internal/struct-markdown).

**Comment by vtorhonen** [comment]
Documentation updated and latest version 1.3.0 released at #25. We'll work on the remote-docs PR next.

**Comment by vtorhonen** [comment]
Docs ingestion PR ready at https://github.com/hashicorp/packer/pull/11587
