### ISSUE TITLE
Error fetching storages

### ISSUE THREAD

**Issue by ojnny** [UpCloudLtd/packer-plugin-upcloud#16]
Hi!

I get the error message when building:
`==> upcloud.test: Error retrieving storage by uuid "01000000-0000-4000-8000-000030200200": Error fetching storages: Get "https://api.upcloud.com/1.3/storage/01000000-0000-4000-8000-000030200200": dial tcp: lookup api.upcloud.com on [::1]:53: read udp [::1]:49436->[::1]:53: read: connection refused
Build 'upcloud.test' errored after 235 milliseconds 846 microseconds: Error retrieving storage by uuid "01000000-0000-4000-8000-000030200200": Error fetching storages: Get "https://api.upcloud.com/1.3/storage/01000000-0000-4000-8000-000030200200": dial tcp: lookup api.upcloud.com on [::1]:53: read udp [::1]:49436->[::1]:53: read: connection refused`

My config:
```
variable "username" {
    type = string
    default = "myapiuser"
}

variable "password" {
    type = string
    default = "myapipassword"
}

packer {
    required_plugins {
        upcloud = {
            version = ">=v1.0.0"
            source = "github.com/UpCloudLtd/upcloud"
        }
    }
}

source "upcloud" "test" {
    username = "${var.username}"
    password = "${var.password}"
    zone = "nl-ams1"
    storage_uuid = "01000000-0000-4000-8000-000030200200"
}

build {
    sources = ["source.upcloud.test"]
}
```

Packer version 1.7.8 and it validates ok. I've double checked the api credentials.

Any help would be much appreciated.

**Comment by Darep** [comment]
Hmm, error message mentions "lookup api.upcloud.com" and port :53 (used by the DNS protocol) so this might be a DNS problem 🤔  😊

**Comment by vtorhonen** [comment]
Looks like a temporary DNS issue indeed. No follow-up or other comments about it so I will go ahead and close this off. 

FYI @ojnny please let us know if this is still an issue.
