### ISSUE TITLE
Unable to find the public IPv4 address of the server

### ISSUE THREAD

**Issue by nekinie** [UpCloudLtd/packer-plugin-upcloud#19]
When using IPv6 only, provisioner errors with:
==> upcloud: Unable to find the public IPv4 address of the server

**Comment by nekinie** [comment]
Problem seems to be at: https://github.com/UpCloudLtd/packer-plugin-upcloud/blob/1d5094fa27fffa2059a033a5e15a5f03a1ccc996/internal/utils.go#L22

**Comment by vtorhonen** [comment]
Thank you for reporting this @nekinie. This will be fixed by #23 once it's merged in.

**Comment by vtorhonen** [comment]
Fixed in the latest plugin version v1.3.0 which was released today.
