### ISSUE TITLE
Builds fail when publishing to HCP Packer

### ISSUE THREAD

**Issue by tomasbasham** [UpCloudLtd/packer-plugin-upcloud#28]
When building an image and publishing build metadata to HCP Packer the post-processing stage fails and this in turn cleans up all the work done by the UpCloud Packer plugin. Effectively the image build succeeds - I know this to be true as I am able to view all the assets in the UpCloud dashboard, but when the post-processing stage kicks in the process fails with the following message:

```bash
Build 'upcloud.puppet_agent' errored after 22 minutes 21 seconds: 1 error(s) occurred:

* Post-processor failed: [TRACE] failed to update Packer registry with image artifacts for "upcloud.puppet_agent": setting a build to DONE with no published images is not currently supported.
```

This error only appears to happen with 3rd party plugins - plugins that were not created by HashiCorp - I suspect this because I am receiving the same error for another 3rd party Packer plugin for a different cloud provider, whilst all the HashiCorp providers run to completion.

My Packer configuration is as follows:

```bash
$ packer -version
1.8.0
```

```hcl
packer {
  required_plugins {
    digitalocean = {
      version = ">= 1.0.4"
      source  = "github.com/hashicorp/digitalocean"
    }
    upcloud = {
      version = ">= v1.2.0" # resolved to v1.3.1
      source  = "github.com/UpCloudLtd/upcloud"
    }
}

build {
  hcp_packer_registry {
    bucket_name = "puppet-agent-almalinux"
    description = <<EOT
AlmaLinux OS image preconfigured with the puppet agent.
EOT

    bucket_labels = {
      "owner" = "platform-team"
      "os"    = "AlmaLinux"
    }

    build_labels = {
      "build-time"   = timestamp()
      "build-source" = basename(path.cwd)
      "rhel-version" = "8"
    }
  }

  sources = [
    "source.digitalocean.puppet_agent",   # This works but is a plugin made by HashiCorp
    "source.upcloud.puppet_agent",
  ]

  provisioner "shell" {
    inline = [
      "echo hello",
    ]
  }
}

source "upcloud" "puppet_agent" {
  username = "${var.upcloud_username}"
  password = "${var.upcloud_password}"

  storage_uuid = "${var.upcloud_image}"
  zone         = "${var.upcloud_zone}"
  ssh_username = "root"

  template_prefix = "puppet-agent-${local.build_time}"
  clone_zones     = var.upcloud_zones

  # The default state_timeout_duration (5m) is not enough for cloning the image
  # across zones. It has been adjusted to accommodate.
  state_timeout_duration = "25m"
}
```

As mentioned the image build actually succeeds but the publishing of the metadata appears to be causing the errors to be printed. Has this plugin been updated to work with the HCP Packer registry?

**Comment by peknur** [comment]
Hi @tomasbasham !

Thank you for reporting this issue and sorry for late response. We now have support for HCP image metadata in our latest 1.5.0 release.
