### ISSUE TITLE
Recommended JSON -> HCL2 upgrade breaks down

### ISSUE THREAD

**Issue by bbros-dev** [UpCloudLtd/packer-plugin-upcloud#4]
The README.md recommended JSON -> HCL2 upgrade  path breaks the conversion tool:

```
$ packer hcl2_upgrade ubuntu-18.04-chef0-development-amd64-commented.json 
unknown builder type: "upcloud"
```

We've also reported out experience in the [Packer community](https://discuss.hashicorp.com/t/working-json-breaks-hcl2-upgrade-unknown-builder-type-builder-missing-type/24398/2) in the hope someone has actually succeeded to migrate.

**Comment by maxfrei** [comment]
@bbros-dev hello! Looks like Hashicorp fixed the issue and will allow upgrade for unknown (not installed) plugins.
https://github.com/hashicorp/packer/pull/11049
