### ISSUE TITLE
 error initializing builder 'upcloud': Unknown builder upcloud

### ISSUE THREAD

**Issue by bbros-dev** [UpCloudLtd/packer-plugin-upcloud#5]
We can't convert a JSON for Packer < `1.7.0` to HCL2 due to issue #4 .

How do we convert a JSON definition for Upcloud used with from Packer `<1.7.0` to use it with Packer `>1.7.0`:

Note using a previously working JSON definition breaks with Packer `1.7.2`:

```
error initializing builder 'upcloud': Unknown builder upcloud
```

**Comment by bbros-dev** [comment]
Upstream is investigating this in hashicorp/packer/issues/11028 - not clear to me where responsibility lies.

**Comment by maxfrei** [comment]
Fixed by Hashicorp https://github.com/hashicorp/packer/pull/11049
