### ISSUE TITLE
The attribute hostname has an invalid value. (HOSTNAME_INVALID)

### ISSUE THREAD

**Issue by bbros-dev** [UpCloudLtd/packer-plugin-upcloud#8]
More sleuthing required to work out what is being objected to....

```
==> upcloud.cicd_upcloud: Creating server based on storage "Ubuntu Server 20.04 LTS (Focal Fossa)"...==> upcloud.cicd_upcloud: Error creating server: The attribute hostname has an invalid value. (HOSTNAME_INVALID)                                                               
Build 'upcloud.cicd_upcloud' errored after 2 seconds 651 milliseconds: Error creating server: The attribute hostname has an invalid value. (HOSTNAME_INVALID)
                                                                
==> Wait completed after 2 seconds 651 milliseconds             
```

The hostname is not an input value.
It is not documented how `hostname` is constructed from values that are provided.
Consequently, how do we work out what to change?

**Comment by maxfrei** [comment]
@bbros-dev hello! Do you use any value in `template_prefix` field? If provided we use it as a `hostname` during server creation.

**Comment by bbros-dev** [comment]
Yes, that is correct, we eventually worked this out by much trial and error.   There also seems to be a character size limit?

**Comment by maxfrei** [comment]
@bbros-dev yes, hostname has 128 characters limit.

Could you please help me summarize what we need to fix:
* add to readme that upcloud plugin needs to be installed before upgrading JSON -> HCL2 (if config depends on upcloud plugin) #4 
* fix: using `template_prefix` for server creation (hostname, storage name) current #8 and related #7 
* upgrade upcloud packer sdk to 1.7.2. probably could solve #5 #6

**Comment by bbros-dev** [comment]
Given you have a pre-`1.7` provider I think you need to provide a **comprehensive** test case JSON showing all the upgrade steps and confirming they work for 1.7.0, 1.7.1, 1.7.2.
possibly a seperate document or in this README.md.

As a general comment the doc's are incomplete.  When using the prlugin docs I shouldn't have to go sluething via google to find out what values are legal and which not.  I can't recall a single link to a reference, and if I've forgotten the link it was probably because it was not really helpful.

Sorry for the harsh feedback - I wasted hours on what should be a trivial exercise.

**Comment by maxfrei** [comment]
Fixed in https://github.com/UpCloudLtd/packer-plugin-upcloud/pull/10

**Comment by bbros-dev** [comment]
I've posed some questions in #10.
