### ISSUE TITLE
macOS arm64 release - Macs with M1

### ISSUE THREAD

**Issue by udaykor** [UpCloudLtd/packer-plugin-upcloud#9]
Hello, 

I would like to request for macOS arm64 release to be included in the release. I have now switched to using packer Mac amd64 to be able to download the current release for Mac amd64. 

Please release arm64 version so that I can switch to using arm binary for both packer and Upcloud plugin

**Comment by maxfrei** [comment]
@udaykor hello! please check out release 1.1.0
https://github.com/UpCloudLtd/packer-plugin-upcloud/releases/tag/v1.1.0
